settings_version: 0.0.4
datasets_dir: ''
weights_dir: C:\Users\shabi\weights
runs_dir: C:\Users\shabi\runs
uuid: 5962ee791c4002fe4e989235ca36ee829417fb9de3161d911556be8e21c7153e
sync: true
api_key: ''
openai_api_key: ''
clearml: false
comet: false
dvc: false
hub: false
mlflow: false
neptune: false
raytune: false
tensorboard: false
wandb: false
